server:
  port: 8081
  context-path: /weixin

weixin:
    appid: 123456
    key: yeyrew



#alibaba的druid数据库连接池配置
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://121.196.222.188:3306/parking?useUnicode=true&characterEncoding=utf8
        username: root
        password: cabin8879576
#        url: jdbc:mysql://rm-bp136s27et5bnt726o.mysql.rds.aliyuncs.com:3306/parking?useUnicode=true&characterEncoding=utf8
#        username: cabin
#        password: cabin8879576aA
        # 使用druid数据源
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20


#spring data jpa 数据源配置
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/mydb
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

mybatis:
  mapper-locations: classpath:mapping/*.xml
#  type-aliases-package: com.weixin.pojo
#  config-location: classpath:mapping/mybatis-config.xml


#日志配置
logging:
  config: classpath:logback.xml

config:
  prod_url: https://eco.taobao.com/router/rest
  app_key: 23305258
  app_secret: 29cd2e8efe075b13abe316e8ed87af13
  sms_type: normal
  sms_free_sign_name: 一咻停车
  rec_num: 18757416607
  sms_template_code: SMS_78595194
